debugging

diff --git a/.github/workflows/create-release-notion-document.yml b/.github/workflows/create-release-notion-document.yml
--- a/.github/workflows/create-release-notion-document.yml
+++ b/.github/workflows/create-release-notion-document.yml
@@ -24,10 +24,6 @@ jobs:
           gem install bundler
           bundle install
 
-      - name: Install jq
-        run: |
-          sudo apt-get install jq
-
       - name: Query GitHub GraphQL API
         id: get-release
         run: |
@@ -54,6 +50,12 @@ jobs:
           github_response=$(curl -sS --http1.1 -X POST -H "$github_headers" -d "{\"query\":\"$query\"}" $github_api_url)
           
           echo "$github_response"
+
+          error_message=$(echo "$github_response" | jq -r '.errors[0].message')
+          if [ ! -z "$error_message" ]; then
+            echo "Error in GraphQL response: $error_message"
+            exit 1
+          fi
 
           # Extract individual fields from the JSON response
           release_name=$(echo "$github_response" | jq -r '.data.repository.releases.nodes[0].name')
